version: '3'

services:
  db-mysql:
    image: mysql:${MYSQL_IMAGE_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_USER_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: ${MYSQL_DB_NAME}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./db-volume:/var/lib/mysql