version: '3'

services:
  db-mongo:
    image: mongo:${MONGO_IMAGE_VERSION}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_USER_PASSWORD}
    container_name: ${MONGO_DB_NAME}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./db-volume:/var/lib/postgresql/data
    command: ['--auth']